### ISSUE TITLE
Octoscreen service is running but no interface on the screen

### ISSUE THREAD

**Issue by rcsez** [Z-Bolt/OctoScreen#125] opened 2020-04-30 22:18 UTC
I've got my 480x320 screen configured on a Pi 3 B+, I added the graphical environment to Octopi 0.17.0, and it booted with autologin to the GUI. However, once I install Octoscreen, the Pi display just goes to a pi@octopi prompt and freezes.

I can access http://octopi.local just fine, and the Octoscreen service shows as active (running) when I SSH into the Pi. The Octopi browser page actually gives me a constant 'Error connecting to printer' notice so Octoscreen is alive, but it just won't display on the touchscreen.

The /boot/config.txt file has been updated to hdmi_cvt 800 533 60 6 0 0 0, and I commented out the original resolution at the bottom of the file.

What can I do to fix this?

**Comment by pjratl** [comment] 2020-05-01 23:55
having the same issue with this screen https://www.amazon.com/gp/product/B07N38B86S/
during boot the text shows on the screen but then nothing

**Comment by pjratl** [comment] 2020-05-02 02:12
Ok I fixed my issue not sure of the exact steps but my issues was FBCP was not running I ended up editing /etc/rc/local and fully qualifying it in my case /usr/local/bin/fbcp/fbcp after installing/reinstalling it...

**Comment by rcsez** [comment] 2020-05-04 23:35
> Ok I fixed my issue not sure of the exact steps but my issues was FBCP was not running I ended up editing /etc/rc/local and fully qualifying it in my case /usr/local/bin/fbcp/fbcp after installing/reinstalling it...

Thanks! For some reason FBCP wasn't running, and starting it up did the trick.

**Comment by Morcegolas** [comment] 2020-05-08 15:39
Hello, my service is also running but I have no interface on the screen, what is FBCP and how do I install it?

Thanks.

**Comment by pjratl** [comment] 2020-05-08 17:36
hope this helps https://github.com/tasanakorn/rpi-fbcp

**Comment by hrqiang** [comment] 2020-05-09 18:15
I get the screen showing properly, but the touch is not working. 
Anyone know how to fix?

**Comment by JeffB42** [comment] 2020-12-04 06:49
@rcsez Could you follow the steps listed in the wiki (located at https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen) and then post a reply to this issue whether the steps listed work and the issue is resolved?  I'd like to start closing out all the display-related issues.

If it doesn't work,
1) make sure you use a Raspberry Pi 3B or Raspberry Pi 4
2) start with a fresh install of OctoPi
3) please take a picture of the screen

Thanks, 

Jeff

**Comment by JeffB42** [comment] 2021-01-02 19:07
@rcsez Is this still an issue?

**Comment by JeffB42** [comment] 2021-02-04 07:16
Closed due to inactivity.

**Closed by JeffB42** 2021-02-04 07:16 UTC
Labels: Display
