### ISSUE TITLE
Screensaver?

### ISSUE THREAD

**Issue by mjgtp** [Z-Bolt/OctoScreen#96] opened 2020-02-27 23:24 UTC
Been using OctoScreen for a short time, but noticed the screen never sleeps.  Is this something configurable or an oversight?  Some of these prints can take days and having the screen on with the icons in the same place could result in burn-in.  Thoughts?

**Comment by bolsoncerrado** [comment] 2020-03-06 15:12
Im also curious!

**Comment by daimon82** [comment] 2020-03-15 00:28
Me too.

**Comment by OutspokenPlanet** [comment] 2020-03-18 14:47
Me three.

**Comment by tekmad** [comment] 2020-04-15 11:05
Screen sleep would be nice.

**Comment by mrkag** [comment] 2020-05-23 17:08
I would love to see a dimly lit Octoprint mascot (does it have a name?) bouncing around the screen when the printer isn't in use.

**Comment by pitchuk** [comment] 2020-05-27 12:19
Me too, been trying to find a way to do this for ages

**Comment by daimon82** [comment] 2020-05-27 12:27
I managed to implement simple screen saver by editing the xorg config:
sudo nano /etc/X11/xorg.conf

and paste the following code:

Section "ServerFlags"
Option "blank time" "5"
Option "standby time" "10"
Option "suspend time" "15"
Option "off time" "20"
EndSection

**Comment by ChaosBlades** [comment] 2020-05-27 12:46
Pretty sure this project is dead. No commits since December of last year. OctoDash has had a screensaver for quite a while and is in active development.

https://github.com/UnchartedBull/OctoDash

**Comment by JeffB42** [comment] 2020-07-31 01:49
This issue is a duplicate of https://github.com/Z-Bolt/OctoScreen/issues/132

**Closed by JeffB42** 2020-07-31 01:49 UTC
