### ISSUE TITLE
no octoprint presets loaded by octoscreen

### ISSUE THREAD

**Issue by FGOD1983** [Z-Bolt/OctoScreen#360] opened 2023-03-03 06:56 UTC
Somehow, since a few weeks I am unable to see the presets from Octoprint in Octoscreen. I can still heat up with the increase temperature, but hitting the bed/hotend or going to temperature and then presets, there is nothing happening or to be seen.

I also tried adding a new preset in Octoprint, but that too is not seen in Octoscreen

**Comment by the-ress** [comment] 2023-06-11 21:08
I had the same issue - it was caused by OctoPrint taking over 3 seconds to respond and OctoScreen gave up.
#347 should fix the issue when it's merged (unless yours is caused by something else).

**Comment by FGOD1983** [comment] 2023-06-12 04:06
Oh wow, I'll try to update it today and see if that fixes it, thx!

**Comment by FGOD1983** [comment] 2023-06-12 05:24
Thx! That did fix it indeed!
![IMG_20230612_072355142](https://github.com/Z-Bolt/OctoScreen/assets/18098873/ee325e04-8f6f-40c3-bcab-ca9004793b64)

**Comment by JeffB42** [comment] 2023-06-20 02:39
https://github.com/Z-Bolt/OctoScreen/pull/347 was merged in, so this should be fixed now.

**Closed as completed by JeffB42** 2023-06-20 02:39 UTC
Labels: 2.8
