### ISSUE TITLE
Screen shifted

### ISSUE THREAD

**Issue by samd12** [Z-Bolt/OctoScreen#104] opened 2020-03-11 01:34 UTC
I have a 7" pi screen but the image is shifted.  Any ideas?  See image
![osup](https://user-images.githubusercontent.com/4117470/76373518-f3446e80-6316-11ea-9598-c05db20e2699.jpg)

**Comment by fidel3d** [comment] 2020-03-14 19:16
![OctoScreen_Printing_screen_shift](https://user-images.githubusercontent.com/26253699/76688803-8c140c00-65ed-11ea-81e0-99ee305fccc4.jpg)
I have the same issue, but it is only on the printing screen. The rest of the screens are fine as far as I can see. 
Here is my setup:
- Raspberry PI 3 A
- Latest on Octoprint and Raspian
- HyperPixel 4 rectangular

Thanks,

**Comment by fidel3d** [comment] 2020-03-14 20:40
Hi,

I guess this fixed the issue with the printing screen shifting to the right.

https://github.com/mkutscher/OctoScreen/releases

Thanks,

**Comment by HaMu56** [comment] 2020-03-20 11:34
Hello from Germany
and sorry if my englisch is not the best
I have a PI4 with the newest octoprint image. all works fine .
now i want to install octoscreen to use a 7inch touchdisplay with a resolution of 1024 x 600. input HDMI and USB for power and touchsignals for the pi4. that all works.
octoscreen is 4.6.1
I tried many resolutions, but on the right the screen is cropped, sometimes more, sometimes less. for this I changed the /boot/config.txt and / etc/octoscreen/config. the PI 4 is set to 720x480 (16: 9) with mode 3.

can you please help me or is the matter still under construction?

THX
Hardy 

[octoscreen.txt](https://github.com/Z-Bolt/OctoScreen/files/4359254/octoscreen.txt)
![20200319_190046](https://user-images.githubusercontent.com/30160317/77160141-130e2c00-6aa7-11ea-94d4-e1b9253ac206.jpg)
![20200319_190028](https://user-images.githubusercontent.com/30160317/77160156-199ca380-6aa7-11ea-828b-a67be8d88fc3.jpg)
![20200320_105359](https://user-images.githubusercontent.com/30160317/77160175-1e615780-6aa7-11ea-9a6a-4b92631f7299.jpg)

**Comment by fidel3d** [comment] 2020-03-22 03:51
Hi Hardy,

Perhaps, I was luck, but one think that I did was to make an image of sd so if I break it I can always go back to it which I did because of the setting, plugins, updates and upgrade in case  I broke something after I tried all the "helps" from difference sources.

Then went back and I strictly follow the instruction from the manufacture (HyperPixel 4 rectangular) and then I tried only the installation from the git, but I used subjection from the url  https://github.com/mkutscher/OctoScreen/releases

so it worked for me so may you should try again.

Good Luck,

Thanks,

**Comment by rwaspe** [comment] 2020-05-24 18:59
It may be the length of your filenames. I posted a fix here: https://github.com/Z-Bolt/OctoScreen/issues/126

**Comment by 3Dietrich** [comment] 2020-09-26 19:00
Hi all, especially  @HaMu56  
I have **exatly** the same problem. I tried several hours to get the right resolution - no success, although everything was clear: [the display](https://smile.amazon.de/gp/product/B07QKT6L58) has 1024x600, even the pi config setting was given 
hdmi_group = 2
hdmi_mode = 87
hdmi_cvt 1024 600 60 6 0 0 0
Setting the OCTOSCREEN_RESOLUTION=1024x600 in /etc/octoscreen/config
resulted in totaly wrong resolution (see att.pictures)
I couldnt find a fitting resolution, although I tried a lot. And _NO, I did not try to load any (longed named) files_ (I didn't came to the point I want to use it, the files also seem 2b empty, but thats a different topic). No. It's just the display size.
Here are some results of OCTOSCREEN_RESOLUTION tests:
![48BA1D1B-1146-498B-8949-617C11B8415B_1_105_c](https://user-images.githubusercontent.com/4608796/94348226-cd748200-003a-11eb-9147-f6c6d2b4d21f.jpeg)
![613A5474-5780-4646-84B1-FDEBB8CA8CEF_1_105_c](https://user-images.githubusercontent.com/4608796/94348227-ce0d1880-003a-11eb-9541-3a9e260a4439.jpeg)

![360A3B1F-6A0C-4AC4-95BF-2A4B6B6F4B47_1_105_c](https://user-images.githubusercontent.com/4608796/94348223-cb122800-003a-11eb-82a4-ba520459aeac.jpeg)

![3FA3A927-CE11-4340-846C-99B11CC94862_1_105_c](https://user-images.githubusercontent.com/4608796/94348228-cea5af00-003a-11eb-8c3e-caf401ed42c5.jpeg)
![2F99DEA2-2F45-405E-9E6D-01491FF86E7E_1_105_c](https://user-images.githubusercontent.com/4608796/94348229-cea5af00-003a-11eb-8d1f-1df7ad89ffcb.jpeg)
![9B340396-E43B-4E05-A903-5444618230E6_1_105_c](https://user-images.githubusercontent.com/4608796/94348230-cf3e4580-003a-11eb-8af7-6bc1f556fe3a.jpeg)
![DDA39556-9F86-4055-B880-BE91570967E1_1_105_c](https://user-images.githubusercontent.com/4608796/94348231-cf3e4580-003a-11eb-80f2-d8d6eee46a31.jpeg)
![A64F8521-43BC-42C0-B07E-7F70405BA7E8_1_105_c](https://user-images.githubusercontent.com/4608796/94348234-cfd6dc00-003a-11eb-8b18-8f8d4fcfacb5.jpeg)
![D4A0F04C-CB38-4CBB-91D5-F95BB8B6BA75_1_105_c](https://user-images.githubusercontent.com/4608796/94348235-d06f7280-003a-11eb-8436-8562d44e6a52.jpeg)

![6F93BB57-577C-43E3-910D-62625E485C4B_1_105_c](https://user-images.githubusercontent.com/4608796/94348236-d06f7280-003a-11eb-8ef4-4ada5066c5ac.jpeg)
![D49DDB7A-38C5-4A93-BB53-2C1B34CD4488_1_105_c](https://user-images.githubusercontent.com/4608796/94348237-d1080900-003a-11eb-9d12-272087263812.jpeg)

**Comment by JeffB42** [comment] 2020-09-27 01:31
Hi @3Dietrich , thanks for posting the details and the pictures, and thanks for trying different resolutions.

The screen shift issue that's been reported most of the time is when a person is running OctoSceen on a small display that's only 480x320.  What's happening, is that OctoScreen uses a Linux GUI library called, GTK.  When OctoScreen runs, it creates a main/central window object, and that window object takes up the entire screen.

When a control or text is displayed and there isn't enough to display it, GTK automatically resizes the window.  If one was running on a desktop, this wouldn't be an issue, but since this "window" takes up the entiure screen, it's expanded past the size of the screen.  That's why the screen appear to be "shifted" and "offscreen".

With your case though, you have a larger display, and everything should work.  I don't have a 1024x600 display myself to test this on, but I can run OctoScreen locally on my desktop computer, and I verified that when OCTOSCREEN_RESOLUTION is set to 1024x600, it runs fine and window doesn't expand.

I don't know if this will work, but try this:
First, comment this out
```
hdmi_cvt 1024 600 60 6 0 0 0
```

I suspect (though I'm not positive) that hdmi_cvt is used for HDMI displays that don't have enough pixels, and a soft scale is applied.  (and this only works with screens which use HDMI)

Thy that, and that does't work, also try commenting out 
```
hdmi_group = 2
hdmi_mode = 87
```
...and see if that works.  In my config, I don't have any of those set.  (I'm also running 800x480)

Next, watch Chris Riley's video on setting up OctoScreen with a HyperPixel display - https://www.youtube.com/watch?v=OJ59hXSyBoI&t=72s.  It's specifically addresses the HyperPixel, but there is quite a lot of good tips & suggestions in it, and I think they might be applicable to your screen.

Please try these out and report back if it works (and what you did)

**Comment by 3Dietrich** [comment] 2020-09-27 12:13
hm.. 
as I [read in raspi docs](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md), the lines
```
hdmi_group = 2
hdmi_mode = 87
hdmi_cvt = 1024 600 60 6 0 0 0
```
belong together, the `hdmi_mode = 87` (in short) doesn't exist, but signs that `hdmi_cvt` entry/numbers are expected.
btw: in last post there is a "=" missing after `_cvt`, also in [amazons product description](https://smile.amazon.de/gp/product/B07QKT6L58) (of course I used the correction).

However, i tried your suggestion:

1. removed only `hdmi_cvt`, no change.
2. removed all 3 `hdmi...`, (actually I started with this setting yesterday): no change

Then I watched [the video](https://www.youtube.com/watch?v=OJ59hXSyBoI). But I couldn't find any help for me. I did not need to install "hyperpixel4" or rotate my screen, in fact the screen worked directly out of the box watching Debian boot-list and terminal (..it's made for raspi). I started to edit all this stuff only to get Octoscreen working.
The rest of the video he explains [the same is written here](https://github.com/Z-Bolt/OctoScreen/tree/master)..

At the end, on my original Raspi Display with crazy 1024x600 pixel, Octoscreen still works "_best_" with 400x400 :(
At least I can use almost all screens, only the "Network information" has no exit:
![172B9956-03C9-4EBD-A96A-8AC5780DF063_1_105_c](https://user-images.githubusercontent.com/4608796/94364304-8b921d00-00c8-11eb-9d6c-41d1eed724fa.jpeg)

I will let you know when I have found a solution

**Comment by JeffB42** [comment] 2020-09-27 21:23
@3Dietrich thanks for investigating.  I don't have a solution/fix yet, but here are some comments:

First, your screen resolution: It's strange... you really shouldn't need to set the resolution down to 400x400, and I'm not sure why you are seeing the window resizing when you run at 1024x600.  I suspect there is a config not set correctly in your system.  When I run (in my development environment) and set OCTOSCREEN_RESOLUTION to 1024x600 it's running fine, and it (the window) never expands.  I suspect that even though your screen's pixels are 1024x600, there's a configuration setting somewhere that's configuring the HDMI to scale down to something smaller (so, even though yo have a 1024x600, the screen might only be set to something like 480x320, and then the 480x320 window is scaled up to 1024x600 on the hardware... not sure though, it's just a hunch)

Second, I was able to reproduce your issue with the Network screen, and the issue is that 400x400 pixels just isn't enough to display that screen.  I switched over the the 2.5.1 codebase (just to make sure and compare "apples-to-apples"), set the resolution to 400x400 and then ran.  Here's what I observed:

It starts up in 400x400:
![OctoScreen-1-StartUp-400x400](https://user-images.githubusercontent.com/10328858/94375608-b92b9600-00c9-11eb-812e-c16faa98c625.png)

...but that's not enough pixels to display the Idle screen, and the window is immediately expanded to 584x400:
![OctoScreen-2-IdlePanel-584x400](https://user-images.githubusercontent.com/10328858/94375622-c9dc0c00-00c9-11eb-900a-d555508e2096.png)

I then navigated to the Network screen, and the window was expanded to 714x400:
![OctoScreen-3-NetworkPanel-714x400](https://user-images.githubusercontent.com/10328858/94375645-f859e700-00c9-11eb-8d02-d398eb73f2b6.png)

I did some image editing, and judging from the screenshot you last posted, it looks like your display is running at (roughly) 594x297:
![OctoScreen-4-NetworkPanel-714x400-shadowed](https://user-images.githubusercontent.com/10328858/94375939-09a3f300-00cc-11eb-84c7-7a8b513594de.png)

594x297 is almost 600x300, and my selection was just an approximate... I suspect that somewhere, something is setting the screen to 600x300, or is scaling the screen by 60% x 50%.

**Comment by JeffB42** [comment] 2020-12-04 06:50
@samd12 Could you follow the steps listed in the wiki (located at https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen) and then post a reply to this issue whether the steps listed work and the issue is resolved?  I'd like to start closing out all the display-related issues.

If it doesn't work,
1) make sure you use a Raspberry Pi 3B or Raspberry Pi 4
2) start with a fresh install of OctoPi
3) please take a picture of the screen

Thanks, 

Jeff

**Comment by JeffB42** [comment] 2021-01-02 19:20
@samd12 is this still an issue?

**Comment by JeffB42** [comment] 2021-02-04 07:28
Closed due to inactivity.

**Closed by JeffB42** 2021-02-04 07:28 UTC
Labels: Display
