### ISSUE TITLE
Custom actions not show on Actions Page

### ISSUE THREAD

**Issue by kizza42** [Z-Bolt/OctoScreen#68] opened 2019-12-15 00:23 UTC
I use the [Custom Control editor](https://plugins.octoprint.org/plugins/customControl/) plugin to inject custom Gcode commands in to Octoprint. They show nicely in the web interface but not all are displayed on OctoScreen, Would love to be able to trigger the extra commands from there.

![2019-12-15_11-21-40](https://user-images.githubusercontent.com/12605257/70856291-459b0c80-1f2d-11ea-8bc2-9102eaa1ccc5.png)
![2019-12-15_11-21-50](https://user-images.githubusercontent.com/12605257/70856292-459b0c80-1f2d-11ea-87b9-4a00b0ea2cfa.png)
![2019-12-15_11-22-35](https://user-images.githubusercontent.com/12605257/70856293-4633a300-1f2d-11ea-9eb4-2142eb999a03.png)

**Comment by mkutscher** [comment] 2020-01-15 07:19
There seems to be a check which only allows single line command commands (or scripts):
https://github.com/Z-Bolt/OctoScreen/blob/master/ui/control.go#L70

**Comment by BlueHoundInc** [comment] 2020-01-23 04:25
The commands also won't show in the menu if there is only one command with blank lines after it.

**Comment by rikvandersteen** [comment] 2021-01-31 21:19
Is it already possible to add custom gcode   action buttons on the touch screen from octoscreen

**Comment by JeffB42** [comment] 2021-02-28 04:40
The issue is that OctoScreen has limited screen real estate.  When you give a command a long name, OctoScreen displays the name, there isn't enough room, and then the screen is expanded.  See all of the issues people having (in general) on 3.5" 640x480 displays, and their screen expanding and shifting on them.  One thing I could do is truncate the string to a max number of characters.

**Comment by JeffB42** [comment] 2021-03-27 18:56
> The commands also won't show in the menu if there is only one command with blank lines after it.

this was fixed by @thebeline and was fixed in the 2.7.0 release.

**Closed by JeffB42** 2021-03-27 18:56 UTC
Labels: 2.7, bug

**Comment by thebeline** [comment] 2021-03-27 19:24
#love
